jobs:
  include:

# Java step
    - language: java
      before_script:
        - cd replay_parser
        - mkdir features
      script: 
        - mvn -P item_all package
        - java -jar target/item_all.one-jar.jar ../replay_downloader/downloads/6022177534.dem